# Generated by Django 3.2.6 on 2021-08-31 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'anfrage',
                'verbose_name_plural': 'anfragen',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='maximale Bildauflösung 1339x729', upload_to='images/slider', verbose_name='bild')),
                ('location', models.CharField(help_text='maximale Länge 64 Zeichen', max_length=64, verbose_name='ort eintragen')),
                ('price', models.CharField(help_text='maximale Länge 10 Zeichen', max_length=10, verbose_name='preis eintragen')),
                ('square', models.CharField(help_text='maximale Länge 5 Zeichen', max_length=5, verbose_name='qm eingeben')),
            ],
            options={
                'verbose_name': 'slider',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(help_text='maximale Bildgröße 27x27px', upload_to='icons/', verbose_name='icon')),
                ('name', models.CharField(max_length=200, verbose_name='social netzwerk')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(help_text='maximale Bildgröße 290x284', upload_to='images/team', verbose_name='foto')),
                ('first_name', models.CharField(max_length=200, verbose_name='vorname')),
                ('last_name', models.CharField(max_length=200, verbose_name='nachname')),
                ('job', models.CharField(max_length=64, verbose_name='beruf')),
            ],
            options={
                'verbose_name': 'mitarbeiter',
            },
        ),
    ]
