# Generated by Django 3.2.6 on 2021-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='maximal 32 Zeichen', max_length=32, verbose_name='projektname')),
                ('image', models.ImageField(upload_to='images/carousel', verbose_name='bild')),
                ('status', models.CharField(help_text='maximal 64 Zeichen', max_length=64, verbose_name='bauphase')),
                ('location', models.CharField(help_text='maximal 64 Zeichnen', max_length=64, verbose_name='ort eintragen')),
                ('description', models.TextField(help_text='maximal 500 Zeichnen', max_length=500, verbose_name='projektbeschreibung')),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'mitarbeiter', 'verbose_name_plural': 'mitarbeiter'},
        ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(default=1, help_text='maximal 32 Zeichen', max_length=32, verbose_name='projektname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(help_text='maximale Bildgröße 27x27', upload_to='icons/', verbose_name='icon'),
        ),
    ]
