# Generated by Django 3.2.6 on 2021-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210901_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='big_image',
            field=models.ImageField(default=1, help_text='maximale Bildauflösung 1200x800', upload_to='images/carousel', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(help_text='maximale Bildauflösung 775x524', upload_to='images/carousel', verbose_name='bild klein'),
        ),
    ]
