# Generated by Django 4.1.6 on 2024-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_slider_location_alter_slider_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "star",
                    models.PositiveIntegerField(default=0, verbose_name="Bewertung"),
                ),
                ("address", models.CharField(max_length=256, verbose_name="Name")),
                ("review", models.TextField(max_length=500, verbose_name="Name")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "anfrage",
                "verbose_name_plural": "anfragen",
                "ordering": ["-created"],
            },
        ),
    ]
