# Generated by Django 4.1.6 on 2024-03-25 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ["-created"],
                "verbose_name": "Bewertung",
                "verbose_name_plural": "Bewertungen",
            },
        ),
        migrations.AddField(
            model_name="rating",
            name="team",
            field=models.CharField(default=1, max_length=128, verbose_name="Team"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating",
            name="address",
            field=models.CharField(blank=True, max_length=256, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="review",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Nachricht"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="star",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Bewertung",
            ),
        ),
    ]
