# Generated by Django 4.1.6 on 2024-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_rating_options_rating_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="text"),
        ),
    ]
