# Generated by Django 4.1.6 on 2024-03-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_contact_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=128, verbose_name="Stadt")),
                ("region", models.CharField(max_length=128, verbose_name="Bundesland")),
                ("country", models.CharField(max_length=128, verbose_name="Land")),
            ],
        ),
        migrations.AddField(
            model_name="rating",
            name="username",
            field=models.CharField(default=1, max_length=128, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating",
            name="review",
            field=models.TextField(max_length=500, null=True, verbose_name="Nachricht"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="address",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.address",
            ),
        ),
    ]
