# Generated by Django 4.1.6 on 2024-03-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_address_rating_username_alter_rating_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.address"
            ),
        ),
    ]
