# Generated by Django 4.1.6 on 2024-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_rating_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=128, null=True, verbose_name="Stadt"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=128, null=True, verbose_name="Land"),
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Bundesland"
            ),
        ),
    ]
