# Generated by Django 4.1.6 on 2024-04-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_address_city_alter_address_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.address",
            ),
        ),
    ]
