# Generated by Django 4.1.6 on 2024-10-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_team_first_name_remove_team_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallationTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_number",
                    models.PositiveIntegerField(default=1, verbose_name="Team"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="rating",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="app.installationteam",
                verbose_name="Team",
            ),
        ),
    ]
