# Generated by Django 4.1.6 on 2024-11-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_installationteam_alter_rating_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="installationteam",
            options={
                "ordering": ["team_number"],
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
    ]
